[tool.poetry]
name = "cafe"
version = "0.1.0"
description = "Integrative Complexity analysis in text & social media posts."
authors = ["Christopher Gikas <crgikas@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sqlmodel = "^0.0.8"
fastapi = "^0.100.1"
uvicorn = "^0.23.2"
typer = "^0.9.0"
dynaconf = "^3.2.0"
pytest = "^7.4.0"
httpx = "^0.24.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
