[tool.poetry]
name = "cafe"
version = "0.1.0"
description = "Integrative Complexity analysis in text & social media posts."
authors = ["Christopher Gikas <crgikas@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sqlmodel = "^0.0.8"
fastapi = "^0.99.0"
uvicorn = "^0.22.0"
typer = "^0.9.0"
dynaconf = "^3.1.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
