on:
  workflow_dispatch:
  push:
    tags:
      - v*

name: deploy

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - id: auth
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.gcp_credentials_json }}

        - uses: docker/login-action@v1
          with:
            registry: gcr.io
            username: oauth2accesstoken
            password: ${{ steps.auth.outputs.credentials }}

        - uses: snok/install-poetry@v1

        - uses: actions/setup-python@v4
          with:
            python-version: 3.11
            cache: 'poetry'

        - run: poetry install

        - run: poetry run pytest

        - run: |-
            echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://gcr.io

        - run: docker push gcr.io/cafe/cafe


    deploy:
      needs: build
      runs-on: ubuntu-latest
      permissions:
        contents: read
        id-token: write

      steps:
        - uses: actions/checkout@v3

        - uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.gcp_credentials_json }}

        - uses: google-github-actions/deploy-cloudrun@v1
          with:
            service: 'prod-cafe'
            image: 'gcr.io/cafe/cafe'