on:
  workflow_dispatch:
  push:
    tags:
      - v*

name: deploy

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - uses: google-github-actions/auth@v1
          with:
            workload_identity_provider: ${{ gcp_identity_provider }}
            service_account: ${{ secrets.gcp_service_account }}

        - uses: snok/install-poetry@v1

        - uses: actions/setup-python@v4
          with:
            python-version: 3.11
            cache: 'poetry'

        - run: poetry install

        - run: poetry run pytest

        - run: docker build -t gcr.io/cafe/cafe .

        - run: docker push gcr.io/cafe/cafe


    deploy:
      needs: build
      runs-on: ubuntu-latest
      permissions:
        contents: read
        id-token: write

      steps:
        - uses: actions/checkout@v3

        - uses: google-github-actions/auth@v1
          with:
            workload_identity_provider: ${{ gcp_identity_provider }}
            service_account: ${{ secrets.gcp_service_account }}

        - uses: google-github-actions/deploy-cloudrun@v1
          with:
            service: 'prod-cafe'
            image: 'gcr.io/cafe/cafe'